name: Cypress Tests

on: push

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run cy:open
      - name: Artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Slack message success
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
         channel-id: '#general'
         slack-message: "Cy tests"
         payload: |
          {
            "text": "GitHub Action Cypress tests result: ${{ job.status }}\n${{github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                "type": "mrkdwn",
                "text": "GitHub Action Cy tests result: ${{ job.status }}\n${{github.event.head_commit.url }}"
              }
            }
           ]
          }
