name: Cypress Tests

on: [push]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run cy:open
      - name: Artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Slack Notification
        run: curl -X POST -H 'Content-type: application/json' --data '{"text":"Cypress tests"}' ${{secrets.SLACK_WEBHOOK}}
