name: Matrix

on: push
jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: log node version
        run: node -v
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
      - name: Log node version again