name: slack

on: push

jobs:
 slack-test:
   runs-on: ubuntu-latest
   steps:
     - name: Post to a Slack channel
       id: slack
       uses: slackapi/slack-github-action@v1.18.0
       with:
        channel-id: '#general'
        slack-message: "Cy tests }}"
env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
