name: Slack notification

on: [pull_request]

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
     - name: Notify slack success
       if: success()
       env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
       uses: voxmedia/github-action-slack-notify-build@v1
       with:
        channel: app-alerts
        status: SUCCESS
        color: good